update

diff --git a/lib/que/ll/kernel b/lib/que/ll/kernel
--- a/lib/que/ll/kernel
+++ b/lib/que/ll/kernel
@@ -1,12 +1,12 @@
 
-function sp_f_ll() {
+function que/ll() {
   local _mode="${1:-S}"
   local _qbat="${2:-ll.batch.sh}"
 #  local _con=""
 #  local _const=""
 
   if test "${_mode}" = "L" ; then
-    _bat="${2:-pbs.login.sh}"
+    _bat="${2:-ll.login.sh}"
   fi
   if ! test -r "${_bat}" ; then
     msg "Batch file not found"
@@ -22,87 +22,73 @@ function sp_f_ll() {
 
   # submit
   # name
-  echo "#${sp_g_qsub} job_name = ${NAME}"                  >> "${_p_qbat}"
+  echo "#${que_ll_qsub} job_name = ${NAME}"                 >> "${_bat}"
 
   # mail
-  if ! test -z "${QUEUE_MAIL}" && test "${QUEUE_MAIL}" != "runprg" ; then
-    echo "#${sp_g_qsub} notification = ${QUEUE_MAIL}"      >> "${_p_qbat}"
-    if ! test -z "${QUEUE_MAIL_TO}" ; then
-      echo "#${sp_g_qsub} notify_user = ${QUEUE_MAIL_TO}"  >> "${_p_qbat}"
+  if ! test -z "${QMAIL}" && test "${QMAIL}" != "runprg" ; then
+    echo "#${que_ll_qsub} notification = ${QMAIL}"          >> "${_bat}"
+    if ! test -z "${QMAILTO}" ; then
+      echo "#${que_ll_qsub} notify_user = ${QMAILTO}" >> "${_bat}"
     fi
   fi
 
   # time
   if ! test -z "${TIME}" ; then
-    echo "#${sp_g_qsub} wall_clock_limit = ${TIME}"        >> "${_p_qbat}"
+    echo "#${que_ll_qsub} wall_clock_limit = ${TIME}"       >> "${_bat}"
   fi
 
   # memory
   if ! test -z "${MEMORY}" ; then
-    echo "#${sp_g_qsub} requirements=(Memory > ${MEMORY}${sp_g_qms})" >> "${_p_qbat}"
+    echo "#${que_ll_qsub} requirements=(Memory > ${MEMORY}${que_ll_unit})" >> "${_bat}"
   fi
 
   if ! test -z "${NODES}" ; then
-    echo "#${sp_g_qsub} node = ${NODES}"                   >> "${_p_qbat}"
+    echo "#${que_ll_qsub} node = ${NODES}"                  >> "${_bat}"
   fi
 
   if test "${MPIOMP}" = "yes" ; then
     if ! test -z "${SCKTS}" ; then
-      echo "#${sp_g_qsub} tasks_per_node = ${SCKTS}"       >> "${_p_qbat}"
+      echo "#${que_ll_qsub} tasks_per_node = ${SCKTS}"      >> "${_bat}"
     fi
     if ! test -z "${CORES}" ; then
-      echo "#${sp_g_qsub} parallel_threads = ${CORES}"     >> "${_p_qbat}"
-      echo "#${sp_g_qsub} task_affinity = core(${CORES})"  >> "${_p_qbat}"
+      echo "#${que_ll_qsub} parallel_threads = ${CORES}"    >> "${_bat}"
+      echo "#${que_ll_qsub} task_affinity = core(${CORES})" >> "${_bat}"
     fi
   else
     if ! test -z "${TASKS}" ; then
-      echo "#${sp_g_qsub} tasks_per_node = ${TASKS}"       >> "${_p_qbat}"
+      echo "#${que_ll_qsub} tasks_per_node = ${TASKS}"      >> "${_bat}"
     fi
   fi
 
   # other constraints
-  if ! test -z "${QUEUE_CONST}" ; then
-    for _con in ${QUEUE_CONST} ; do
-      echo "#${sp_g_qsub} network.MPI = ${_con}"     >> "${_p_qbat}"
+  if ! test -z "${QCONST}" ; then
+    for _con in ${QCONST} ; do
+      echo "#${que_ll_qsub} network.MPI = ${_con}"          >> "${_bat}"
     done
   fi
 
-  # partition
-  # if ! test -z "${QUEUE_PART}" ; then
-  #  echo "#${sp_g_qsub} bg_partition = ${QUEUE_PART}"  >> "${_p_qbat}"
-  # fi
-
   # project
-  if ! test -z "${QUEUE_PROJECT}" ; then
-    echo "#${sp_g_qsub} account_no = ${QUEUE_PROJECT}" >> "${_p_qbat}"
+  if ! test -z "${QPROJ}" ; then
+    echo "#${que_ll_qsub} account_no = ${QPROJ}"            >> "${_bat}"
   fi
 
   # qos
-  if ! test -z "${QUEUE_QOS}" ; then
-    echo "#${sp_g_qsub} job_type = ${QUEUE_QOS}"    >> "${_p_qbat}"
+  if ! test -z "${QQOS}" ; then
+    echo "#${que_ll_qsub} job_type = ${QQOS}"               >> "${_bat}"
   fi
 
-  # exclusive?
-  # if test "${QUEUE_EXCLUSIVE}" = "yes" ; then
-  #   echo "#${sp_g_qsub} --exclusive"                >> "${_p_qbat}"
-  # fi
+  echo "#${que_ll_qsub} input  = ${QIN:-/dev/null}"         >> "${_bat}"
+  echo "#${que_ll_qsub} output = ${QOUT:-StdOut}"           >> "${_bat}"
+  echo "#${que_ll_qsub} error  = ${QERR:-ErrOut}"           >> "${_bat}"
 
-  echo "#${sp_g_qsub} input = ${QUEUE_STDOUT:-/dev/null}" >> "${_p_qbat}"
-  echo "#${sp_g_qsub} output = ${QUEUE_STDOUT:-StdOut}"   >> "${_p_qbat}"
-  echo "#${sp_g_qsub} error = ${QUEUE_ERROUT:-ErrOut}"    >> "${_p_qbat}"
-
-  # if ! test -z "${QUEUE_OPTS}" ; then
-  #   echo "#${sp_g_qsub} ${QUEUE_OPTS}"              >> "${_p_qbat}"
-  # fi
-
-  echo "#${sp_g_qsub} queue"                              >> "${_p_qbat}"
+  echo "#${que_ll_qsub} queue"                              >> "${_bat}"
 }
 
-function sp_f_qmail_sub() {
+function que/ll/mail/sub() {
   echo "Job ${LOADL_JOB_NAME}"
 }
 
-function sp_f_qmail_msg() {
+function que/ll/mail/msg() {
   local _m=""
   _m=$(date)
   if ! test -z "${LOADL_TOTAL_TASKS}" ; then
